name: Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Logseq Publish
        uses: pengx17/logseq-publish@main
        with:
          version: nightly

      - name: Not Jekyll
        run: touch $GITHUB_WORKSPACE/www/.nojekyll

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: www
          clean: true
          clean-exclude: |
            CNAME
